from .Constants import FILENAME, READ_MODE, WRITE_MODE, TIME_FORMAT, DATE_FORMAT, NAME_FIELD, DATE_FIELD, BUSY_FIELD, STARTTIME_FIELD, TIMEWORKED_FIELD, ALL_FIELDS
from .Ticket import Ticket
from .sharedCode import overWriteFile
